### ISSUE TITLE
Instructions for Linux Setting the UDEV rules

### ISSUE THREAD

**Issue by AshitakaLax** [keyboardio/Kaleidoscope#155]
Currently in Linux when you try to program the keyboard, you will get a programming error.

The error looks similar to this.

> Sketch uses 20684 bytes (72%) of program storage space. Maximum is 28672 bytes.
Global variables use 1700 bytes (66%) of dynamic memory, leaving 860 bytes for local variables. Maximum is 2560 bytes.
processing.app.debug.RunnerException
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:160)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
	at processing.app.SketchController.upload(SketchController.java:713)
	at processing.app.SketchController.exportApplet(SketchController.java:686)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2149)
	at java.lang.Thread.run(Thread.java:745)
Caused by: processing.app.SerialException: Error touching serial port '/dev/ttyACM0'.
	at processing.app.Serial.touchForCDCReset(Serial.java:99)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:144)
	... 5 more
Caused by: jssc.SerialPortException: Port name - /dev/ttyACM0; Method name - openPort(); Exception type - Permission denied.
	at jssc.SerialPort.openPort(SerialPort.java:170)
	at processing.app.Serial.touchForCDCReset(Serial.java:93)
	... 6 more

The wiki doesn't have any instructions on how to add this.
I'm going to add a wiki page on how to add a udev rule to linux. I have done this for work a couple of times.

**Comment by AshitakaLax** [comment]
After playing with it a little bit, I found out that I made the mistake, and it has nothing to do with the udev rules.

I just wasn't holding the Prog button before pressing upload.

This task isn't needed.
